when@dev: &dev
    zenstruck_foundry:
        auto_refresh_proxies: true
        faker:
            locale: pl_PL

when@test:
    zenstruck_foundry:
        auto_refresh_proxies: true
        faker:
            locale: pl_PL
        orm:
            reset: true